apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uy4891krv-nodejs
  janus-idp.io/tekton: uy4891krv-nodejs
  backstage.io/kubernetes-id: uy4891krv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uy4891krv-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
