apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uy4891krv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uy4891krv-nodejs 
  name: uy4891krv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: uy4891krv-nodejs 
